### ISSUE TITLE
`pip install -e` installs the source under the current working directory instead of under the environment directory

### ISSUE THREAD

**Issue by ksze** [jjhelmus/berryconda#12]
I'm used to the behaviour of pip in the system-provided python and virtualenv/virtualenvwrapper, where `pip install -e` a package from git would clone the repo into a subdirectory of the virtualenv. For instance, using virtualenvwrapper, I can do this:

    ~ $ mkvirtualenv foobarenv
    ~ $ pip install -e git+https://github.com/foobar/foobar.git
    ~ $ ls -ld /home/ksze/.virtualenvs/foobarenv/src/
    total 8
    drwxr-xr-x 8 ksze ksze 4096 Jul 31 10:38 foobar
    -rw-r--r-- 1 ksze ksze 185 Jul 31 10:39 pip-delete-this-directory.txt

And foobar's git repo would be cloned into `/home/ksze/.virtualenvs/foobar/src/foobar`, regardless of where I run pip from.

However, using berryconda, `pip install -e` just clones to a subdirectory under the _current working directory_. This behaviour is quite annoying, not to mention being incompatible with what people expect when using a requirements file.

    ~ $ conda create -n foobar pip
    ~ $ source activate foobar
    ~ $ pip install -e git+https://github.com/foobar/foobar.git
    ~ $ ls -ld ./src/
    total 8
    drwxr-xr-x 8 ksze ksze 4096 Jul 31 10:41 foobar
    -rw-r--r-- 1 ksze ksze 185 Jul 31 10:40 pip-delete-this-directory.txt

I'm not sure if this is an upstream conda issue or specific to berryconda, as I have never used the "vanilla" conda.

**Comment by ksze** [comment]
This is what `pip install --help` has to say about installing editable projects:

    --src <dir>                 Directory to check out editable projects into. The default in a virtualenv is "<venv path>/src". The default for global installs is "<current dir>/src".

I also made sure that I'm running pip in the conda environment:

    ~ $ which pip
    /home/ksze/berryconda3/envs/foobar/bin/pip

This suggests that pip somehow doesn't recognize a conda environment as a proper virtualenv.

However, you would probably agree that for all intents and purposes, a conda environment activated by `source activate foobar` should be treated like a plain virtualenv.

**Comment by jjhelmus** [comment]
Unfortunately conda environments are not virtualenv and therefore `pip install -e` results in the default behavior of installing into the current working directory. I agree that it would be nice if conda and virtualenv were more aware of each other. This is not an issue specific to berryconda, the same behavior is seen when using conda on other platforms.  Opening issues upstream with with [pip](https://github.com/pypa/pip), [virtualenv](https://github.com/pypa/virtualenv) or [conda](https://github.com/conda/conda) would be a better place to discuss this topic.

**Comment by Chong-Jiao** [comment]
How can I uninstall it if I install it by "pip install -e ."?

**Comment by mrjamescollins** [comment]
'pip uninstall <module name>'
you can get this name by doing a 'pip list'
