### ISSUE TITLE
holoviews

### ISSUE THREAD

**Issue by seibert** [jjhelmus/berryconda#17]
Now that bokeh-charts has been deprecated in favor of holoviews (which is pretty awesome), it would be nice to have holoviews packages.  I think to be useful also requires packages for param, paramnb, and parambokeh.

**Comment by jjhelmus** [comment]
I agree.  I'll look into getting our some packages this weekend.

**Comment by jjhelmus** [comment]
`holoview` packages as well as `lancet` and `param` packages are now available in the `rpi` channel.  I did not see a need for `paramnd` and `parambokeh` packages although I will keep an eye on those.
