### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by capyy** [jjhelmus/berryconda#2]
Hi Jonathan,

After reading [https://github.com/samjabrahams/tensorflow-on-raspberry-pi](https://github.com/samjabrahams/tensorflow-on-raspberry-pi) and seeing that you published Tensorflow in one of your other channels I am wondering how feasible it is to have Tensorflow in Berryconda. It seems a bit less straightforward than other packages.

Thanks.

**Comment by jjhelmus** [comment]
I believe it would be technically possible to build a tensorflow conda package for the Raspberry Pi. It would require quite a bit of work and I am not planning on working on this task for berryconda.
