### ISSUE TITLE
Update request: Bokeh 0.12.15

### ISSUE THREAD

**Issue by AzraelDD** [jjhelmus/berryconda#22]
> Please report any problems with Berryconda or the packages in the rpi channel by submitting an issue. Also, use this link to request new packages.

I would like to request Bokeh 0.12.15, since only 0.12.13 from December 2017 seems to be available on the rpi channel. I hope this is the right way to go about this. Or should I try to build Bokeh myself?

Many thanks!

**Comment by AzraelDD** [comment]
Thanks for the quick response!

**Comment by jjhelmus** [comment]
bokeh 0.12.15 is now available on the `rpi` channel.
