### ISSUE TITLE
Just curious how this differs from Miniconda

### ISSUE THREAD

**Issue by jorijnsmit** [jjhelmus/berryconda#24]
What would be reasons to choose the one or the other?

**Comment by jjhelmus** [comment]
Miniconda is a great choice for x86 processors.  The packages in those installer are professionally built and kept up-to-date.  The Miniconda installers for armv6 and armv7 have not been updated for some time and contain older versions of Python, conda, etc.  The Berryconda installers have more recent versions of these packages and automatically include the `rpi` channel with even more packages for these platforms.

**Comment by jorijnsmit** [comment]
Thanks, didn't take into account the architecture of the builds. Thanks for your efforts 🙏
