### ISSUE TITLE
Package update request: Pandas

### ISSUE THREAD

**Issue by AzraelDD** [jjhelmus/berryconda#27]
Hi there and thanks again for the great work. 
I would like to kindly request an update for Pandas from 0.22.0 to the latest version (currently 0.23.1), if possible.

Edit: Bokeh 0.13.0 has just been released, too. This would be much appreciated as well.

Cheers

**Comment by jjhelmus** [comment]
Thanks for the request and kind words.  Sorry it took so long to get to this request.
Pandas 0.23.3 and Bokeh 0.13.0 packages are now available on the `rpi` channel.
