### ISSUE TITLE
Install ipyleaflet

### ISSUE THREAD

**Issue by deeplook** [jjhelmus/berryconda#37]
Having ipyleaflet would be awesome giving its recent improvements.

More generally speaking, maybe it would be helpful to provide a section about how to contribute such additional packages as external contributions to this project? Thanks a lot, BTW!

**Comment by gaiar** [comment]
@deeplook, please check - https://anaconda.org/rpi/ipyleaflet/files. It seems @jjhelmus has added package recently.

**Comment by deeplook** [comment]
Awesome, it works! Thanks!!
