### ISSUE TITLE
Numba installing failed 

### ISSUE THREAD

**Issue by NervenCid** [jjhelmus/berryconda#56]
Hello:

Thank you

I tried to install numba using berryconda but i obtained this error:

Loading channels: done

PackagesNotFoundError: The following packages are not available from current channels:

  - numba

Current channels:

  - https://conda.anaconda.org/rpi/linux-armv7l
  - https://conda.anaconda.org/rpi/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Any suggestion?

**Comment by jjhelmus** [comment]
What command did you use to install numba?  Numba is not available in the default `rpi` channel, rather you must specify the extra `numba` channel using `-c numba`.  For example this following command will create a new environment named **numba_env** with numba and Python 3.6: `conda create -n numba_env -c numba python=3.6 numba`
