### ISSUE TITLE
cannot install on aarch64 GNU/Linux

### ISSUE THREAD

**Issue by forhonourlx** [jjhelmus/berryconda#61]
PREFIX=/home/simon/berryconda3
installing: python-3.6.1-0 ...
./Berryconda3-2.0.0-Linux-armv7l.sh: line 212: /home/simon/berryconda3/bin/python: No such file or directory
ERROR:
cannot execute native linux-armv7l binary, output from 'uname -a' is:
Linux localhost 4.9.65-perf+ #2 SMP PREEMPT Wed Jan 9 22:16:26 CST 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by jjhelmus** [comment]
Berryconda supports armv7l or armv6l platforms not aarch64.
