### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by fgr1986** [jjhelmus/berryconda#62]
Hi, it would be interesting to add support to RPI3b+ (with non-raspbian OS as ubuntu or suse) using the arm64 architecture.

Regards

**Comment by jjhelmus** [comment]
`conda-forge` has begun to build  `linux-aarch64` packages which can be used on a Raspberry Pi with a 64-bit OS installed.  Progress can be tracked on the [status page](https://conda-forge.org/status/]).
