### ISSUE TITLE
openssl error message after running 'conda update --all'

### ISSUE THREAD

**Issue by carver7** [jjhelmus/berryconda#64]
<loginname>@<raspberryPisName>:~ $ openssl
WARNING: can't open config file: /home/jhelmus/bc3_v7/conda-bld/openssl_1547610726478/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/ssl/openssl.cnf

**Comment by jjhelmus** [comment]
A prefix in the openssl `libcrypto` library was not getting marked for replacement.  I'll upload correct packages shortly.

**Comment by jjhelmus** [comment]
The openssl 1.0.2r packages now available on the `rpi` channel have a fix for this issue:

```
~$ openssl version
OpenSSL 1.0.2r  26 Feb 2019
~$ openssl
OpenSSL>  
```
