### ISSUE TITLE
Create Conda environment in Raspberry Pi 3 B+ Ubuntu 18.04.2 aarch64 (ARMv8)

### ISSUE THREAD

**Issue by advanchip** [jjhelmus/berryconda#75]
I need to create Conda environment in Raspberry Pi 3 B+ Ubuntu 18.04.2 aarch64 (ARMv8).

I tried Berryconda3

    wget https://github.com/jjhelmus/berryconda/releases/download/v2.0.0/Berryconda3-2.0.0-Linux-armv7l.sh
    md5sum Berryconda3-2.0.0-Linux-armv7l.sh
    bash Berryconda3-2.0.0-Linux-armv7l.sh

and got the error messages:

installing: python-3.6.1-0 ...
./Berryconda3-2.0.0-Linux-armv7l.sh: line 212: /home/alice/berryconda3/bin/python: No such file or directory
ERROR:
cannot execute native linux-armv7l binary, output from 'uname -a' is:
Linux alice-desktop 4.15.0-1049-raspi2 #53-Ubuntu SMP PREEMPT Wed Oct 2 01:04:00 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

Please advise. Any help is highly appreciated.

**Comment by jjhelmus** [comment]
berryconda only supports 32-bit armv7l and armv6l platforms. You are running on a 64-bit aarch64 platform which is not supported.
